# Web Scraping using BeautifulSoup - Assignment 1

1. requests: This will be used to send get request to the webpage server to get the source-code of the web page
2. BeautifulSoup: This will be used to parse the source code and to extract the required data from the parsed structure.

In [173]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd

1) Write a python program to display all the header tags from wikipedia.org

In [174]:
def get_url_header(url):
    res = requests.get(url)
    bs = BeautifulSoup(res.content)
    header = []
    for i in bs.find_all('span',{"class" : "mw-headline"}):
        header.append(i.text)
    print(header)

In [175]:
get_url_header("https://simple.wikipedia.org/wiki/Main_Page")

['Welcome to Wikipedia,', 'About Wikipedia', 'Selected article', 'Did you know...', 'Knowledge groups', 'Sister projects', 'Other languages']

2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year 
of release) and make data frame.

In [176]:
def imdb_top_100(url):
    res=requests.get(url)
    sp=BeautifulSoup(res.content)
    movie=[]
    year =[]
    rating=[]
    for i in sp.find_all('h3',{"class":"lister-item-header"}):
        movie.append(i.text.replace("\n","").strip().split('(')[0].split('.')[1])
    for j in sp.find_all('span',{"class":"lister-item-year text-muted unbold"}):
        year.append(j.text.replace("\n","").strip("()"))
    for k in sp.find_all('div',{"class":"ipl-rating-star small"}):
        rating.append(k.text.replace("\n",""))

    df=pd.DataFrame({"Movie" :movie,"Year of Release":year,"Rating":rating})
    return df

In [177]:
imdb_top_100("https://www.imdb.com/list/ls091520106/")

                                  Movie Year of Release Rating
0              The Shawshank Redemption            1994    9.3
1                         The Godfather            1972    9.2
2                 The Godfather Part II            1974      9
3                       The Dark Knight            2008      9
4                          12 Angry Men            1957      9
..                                  ...             ...    ...
95                   North by Northwest            1959    8.3
96                   A Clockwork Orange            1971    8.3
97                               Snatch            2000    8.2
98  Le fabuleux destin d'Amélie Poulain            2001    8.3
99                              The Kid            1921    8.2

[100 rows x 3 columns]

3) Write a python program to scrape mentioned details from dineout.co.in : i) Restaurant name ii) Cuisine iii) Location iv) Ratings v) Image URL.

In [178]:
def dineout_restaurant_names(url):
    res=requests.get(url)
    sp = BeautifulSoup(res.content)
    name = []
    rating = []
    location = []
    img_url =[]
    cuisine =[]
    for i in sp.find_all('div',{"class":"restnt-info cursor"}):
        name.append(i.text.strip().split(',')[0])
    for j in sp.find_all('div',{"class":["restnt-rating rating-4","restnt-rating rating-5"]}):
        rating.append(j.text)
    for k in sp.find_all('div',{"class":"restnt-loc ellipsis"}):
        location.append(k.text)
    for l in sp.find_all('img',class_="no-img"):
        img_url.append(l["data-src"])
    for m in sp.find_all('span',{"class":"double-line-ellipsis"}):
        cuisine.append(m.text.strip().split("|")[1])
    df1=pd.DataFrame(data={"Restaurant name":name,"Cuisine":cuisine,"Location":location,"Ratings":rating,"Image URL":img_url})
    return df1

In [179]:
dineout_restaurant_names("https://www.dineout.co.in/delhi-restaurants")

,Restaurant name,Cuisine,Location,Ratings,Image URL
0,Delia My Bar HeadquartersKarol Bagh,"North Indian, Chinese, Fast Food, Beverages","Karol Bagh, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
1,My Bar HeadquartersConnaught Place,"North Indian, Chinese","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
2,Berco'sConnaught Place,"Chinese, Thai","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
3,The G.T. RoadM-Block,North Indian,"M-Block,Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,Article 21Connaught Place,"North Indian, Chinese, South Indian","Connaught Place, Central Delhi",3.8,https://im1.dineout.co.in/images/uploads/resta...
5,Punjab GrillJanpath,"North Indian, Mughlai","Janpath, Central Delhi",3.7,https://im1.dineout.co.in/images/uploads/resta...
6,Unplugged CourtyardConnaught Place,"North Indian, Italian, Chinese, Turkish, Cont...","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
7,SliceConnaught Place,"Italian, Fast Food","Connaught Place, Central Delhi",5,https://im1.dineout.co.in/images/uploads/resta...
8,Minar RestaurantConnaught Place,"North Indian, Chinese","Connaught Place, Central Delhi",4.4,https://im1.dineout.co.in/images/uploads/resta...
9,Kwality RestaurantRegal Cinema Complex,"North Indian, Continental, Mughlai","Regal Cinema Complex,Connaught Place, Central ...",4.4,https://im1.dineout.co.in/images/uploads/resta...
10,Nando'sM-Block,"Portuguese, Mediterranean, Desserts, Beverages","M-Block,Connaught Place, Central Delhi",4.4,https://im1.dineout.co.in/images/uploads/resta...
11,Hard Rock CafeConnaught Place,"American, Continental, Finger Food","Connaught Place, Central Delhi",4.9,https://im1.dineout.co.in/images/uploads/resta...
12,SubwayConnaught Place,Fast Food,"Connaught Place, Central Delhi",5,https://im1.dineout.co.in/images/uploads/resta...
13,Fa YianConnaught Place,Chinese,"Connaught Place, Central Delhi",4.8,https://im1.dineout.co.in/images/uploads/resta...
14,Cafe MRPConnaught Place,"North Indian, Continental, Italian, Finger Fo...","Connaught Place, Central Delhi",5,https://im1.dineout.co.in/images/uploads/resta...
15,Oddly PubConnaught Place,"North Indian, Chinese, Italian, Continental","Connaught Place, Central Delhi",5,https://im1.dineout.co.in/images/uploads/resta...
16,LocalScindia House,"North Indian, Asian, Continental","Scindia House,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
17,Kill The BillConnaught Place,"Fast Food, North Indian, Seafood, Chinese, Co...","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
18,SandozConnaught Place,"North Indian, Continental","Connaught Place, Central Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
19,The EmbassyConnaught Place,"North Indian, European, Fast Food, Italian, C...","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
20,Gin & JulietF-Block,"Italian, Chinese, North Indian, Fast Food","F-Block,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...

4) Write s python program to display list of respected former finance minister of India(i.e. 
Name , Term of office) from https://presidentofindia.nic.in/former-presidents.htm and make 
data frame.

In [180]:
def president_of_india(url):
    response = requests.get(url)
    sp = BeautifulSoup(response.content)
    president_name = []
    president_tenure =[]
    for i in sp.find_all("div",class_ ='president-listing'):
        president_name.append(i.text.strip().split("\n")[0])
    for j in sp.find_all("div",class_='president-listing'):
        president_tenure.append(j.text.strip().split("\n")[1])
    df2=pd.DataFrame({"Name of President" :president_name,"Tenure of President":president_tenure})
    return df2

In [181]:
president_of_india("https://presidentofindia.nic.in/former-presidents")

               Name of President      Tenure of President
0           Shri Ram Nath Kovind  14th President of India
1          Shri Pranab Mukherjee  13th President of India
2   Smt Pratibha Devisingh Patil  12th President of India
3         DR. A.P.J. Abdul Kalam  11th President of India
4           Shri K. R. Narayanan  10th President of India
5        Dr Shankar Dayal Sharma  9th  President of India
6            Shri R Venkataraman   8th President of India
7               Giani Zail Singh   7th President of India
8      Shri Neelam Sanjiva Reddy   6th President of India
9       Dr. Fakhruddin Ali Ahmed   5th President of India
10  Shri Varahagiri Venkata Giri   4th President of India
11              Dr. Zakir Husain   3rd President of India
12  Dr. Sarvepalli Radhakrishnan   2nd President of India
13           Dr. Rajendra Prasad   1st President of India